name: Get Citation Data

on: 
 page_build: 
 schedule:
  - cron:  '0 0 * * *'
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Reqs
      run: |
        sudo apt-get install python3-setuptools
    - name: Run
      run: |
        echo "=== Start installing requirements ==="
        date
        cd ./google_scholar_crawler
        pip3 install -r requirements.txt
        echo "=== Finished installing requirements ==="
        date

        echo "=== Start running main.py ==="
        date
        python3 main.py
        echo "=== Finished running main.py ==="
        date

        echo "=== Start git operations ==="
        date
        cd ./results
        git init
        git config --local user.name "${GITHUB_ACTOR}"
        export remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
        git add *.json
        git commit -m "Updated Citation Data"
        git push "${remote_repo}" HEAD:google-scholar-stats --force
        echo "=== Finished git operations ==="
        date
      env: 
        GOOGLE_SCHOLAR_ID: ${{ secrets.GOOGLE_SCHOLAR_ID }}
